
colormsg(HICYAN "")
colormsg(HICYAN "xerces-c")

find_package(XercesC 3.2.0 REQUIRED)

if(${XercesC_FOUND})
    message(STATUS "Found XercesC ${XercesC_VERSION} at ${XercesC_INCLUDE_DIRS} with ${XercesC_LIBRARIES}")
    set(XercesC_Filtered_LIBS "")
    foreach(XercesCLIB ${XercesC_LIBRARIES})
        get_filename_component(XercesCLIB_DIR ${XercesCLIB} DIRECTORY)
        get_filename_component(XercesCLIB_NAME ${XercesCLIB} NAME)
        get_filename_component(XercesCLIB_BASE_DIR ${XercesCLIB_DIR} DIRECTORY)
        if(EXISTS ${XercesCLIB_BASE_DIR})
        else(EXISTS ${XercesCLIB_BASE_DIR})
            message(SEND_ERROR "XercesC base directory does not exist: ${XercesCLIB_BASE_DIR}")
        endif(EXISTS ${XercesCLIB_BASE_DIR})
        set(XercesC_Filtered_LIB "")
        if(EXISTS ${XercesCLIB})
            set(XercesC_Filtered_LIB ${XercesCLIB})
        elseif(EXISTS "${XercesCLIB_BASE_DIR}/lib/${XercesCLIB_NAME}")
            set(XercesC_Filtered_LIB "${XercesCLIB_BASE_DIR}/lib/${XercesCLIB_NAME}")
        elseif(EXISTS "${XercesCLIB_BASE_DIR}/lib64/${XercesCLIB_NAME}")
            set(XercesC_Filtered_LIB "${XercesCLIB_BASE_DIR}/lib64/${XercesCLIB_NAME}")
        endif(EXISTS ${XercesCLIB})
        list(APPEND XercesC_Filtered_LIBS ${XercesC_Filtered_LIB})
    endforeach(XercesCLIB ${XercesC_LIBRARIES})
    if(EXISTS "${XercesC_INCLUDE_DIRS}/../lib")
        set(XERCESC_LIB_DIR "lib")
    elseif(EXISTS "${XercesC_INCLUDE_DIRS}/../lib64")
        set(XERCESC_LIB_DIR "lib64")
    endif(EXISTS "${XercesC_INCLUDE_DIRS}/../lib")
    set(XERCESC_FOUND ${XercesC_FOUND})
    set(XERCESC_LIBRARIES ${XercesC_Filtered_LIBS})
    set(XERCESC_INCLUDE_DIR ${XercesC_INCLUDE_DIRS})
endif(${XercesC_FOUND})
