
#include <icetray/serialization.h>
#include <dataclasses/I3Vector.h>
#include <string>

I3_SERIALIZABLE(I3VectorBool);
I3_SERIALIZABLE(I3VectorUInt8);
I3_SERIALIZABLE(I3VectorUInt16);
I3_SERIALIZABLE(I3VectorUInt32);
I3_SERIALIZABLE(I3VectorUInt64);
I3_SERIALIZABLE(I3VectorInt8);
I3_SERIALIZABLE(I3VectorInt16);
I3_SERIALIZABLE(I3VectorInt32);
I3_SERIALIZABLE(I3VectorInt64);

I3_SERIALIZABLE(I3VectorFloat);
I3_SERIALIZABLE(I3VectorDouble);

I3_SERIALIZABLE(I3VectorString);
I3_SERIALIZABLE(I3VectorOMKey);
I3_SERIALIZABLE(I3VectorTankKey);
I3_SERIALIZABLE(I3VectorModuleKey);
// This is just a typedef for an int:
//I3_SERIALIZABLE(I3VectorStationKey);

I3_SERIALIZABLE(I3VectorCCMPMTKey);
I3_SERIALIZABLE(I3VectorCCMPMTType);

I3_SERIALIZABLE(I3VectorDoubleDouble);
I3_SERIALIZABLE(I3VectorI3Position);

I3_SERIALIZABLE(I3VectorI3VectorDouble);
I3_SERIALIZABLE(I3VectorI3VectorI3VectorDouble);

I3_SERIALIZABLE(I3VectorI3VectorUInt8);
I3_SERIALIZABLE(I3VectorI3VectorUInt16);
I3_EXPORT_EXTRA_KEY(I3VectorI3VectorUInt16, CCMAnalysis::Binary::I3VectorI3VectorUInt16)
I3_SERIALIZABLE(I3VectorI3VectorUInt32);
I3_SERIALIZABLE(I3VectorI3VectorUInt64);

I3_SERIALIZABLE(I3VectorI3VectorInt8);
I3_SERIALIZABLE(I3VectorI3VectorInt16);
I3_SERIALIZABLE(I3VectorI3VectorInt32);
I3_SERIALIZABLE(I3VectorI3VectorInt64);
I3_EXPORT_EXTRA_KEY(I3VectorI3VectorInt64, I3Vector<I3Vector<int64_t>>);

I3_SERIALIZABLE(I3VectorPairBoolInt64);

